//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocıalMedıa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billboard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Billboard()
        {
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int Billboard_id { get; set; }
        public string Billboard_name { get; set; }
        public string Billboard_detail { get; set; }
        public string Billboard_status { get; set; }
        public Nullable<int> Billboard_height { get; set; }
        public Nullable<int> Billboard_width { get; set; }
        public Nullable<int> Loc_id { get; set; }

        public virtual ICollection<Location> Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
