//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocıalMedıa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int Cus_id { get; set; }
        public string Cus_name { get; set; }
        public string Cus_surname { get; set; }
        public string Cus_email { get; set; }
        public string Cus_phonenumber { get; set; }
        [Required(ErrorMessage = "Bu Alan Zorunlu")]
        public string username { get; set; }
        [Required(ErrorMessage = "Bu Alan Zorunlu")]
        public string password { get; set; }
        [Required(ErrorMessage = "Bu Alan Zorunlu")]
        public Nullable<int> Loc_id { get; set; }
        public IEnumerable<Location> loc_names { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservation { get; set; }
    }

}
